### ISSUE TITLE
Question about OneDrive Storager implement

### ISSUE THREAD

**Issue by zxy-lgtm** [beyondstorage/go-service-onedrive#11]
1. authorization
    Because onedrive uses `oauth` authentication, an OAuth instance is required to obtain `accesstoken`. Do we have to do this built-in? My current test environment uses the example of [Microsoft Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer).
    If we need to do a built-in authentication process, I think maybe our `credential` field should be `env`, which contains similar `clientid`, `clientsecret`... 

2. abstract `objectID` to `path`
    Because the current SDKs are all developed according to [OneDrive's development manual](https://docs.microsoft.com/en-us/onedrive/developer/). Onedrive's API objects are basically based on `objectID`, instead of locating a storage object through the traditional `path`.
    So I think there are two ways to achieve `path` abstraction.
    1. Through the search API, putting the search pressure on the onedrive side, but it seems that Microsoft's [bug](https://answers.microsoft.com/en-us/msoffice/forum/all/onedrive-search-not-working/48122e08-b2d5-4420-b786-55b5da393e24?auth=1&page=1) has not been fixed.
    2. Through the given path, traverse each folder to find the target file, but this is more expensive. The only way to think at present is to cache, cache the already known objectid, and check before the operation to ensure consistency.

**Comment by xxchan** [comment]
question 1: see https://github.com/beyondstorage/go-service-gdrive/issues/17

question 2: 

I found that OneDrive do support file path: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online (If I understand incorrectly, please tell me)

> There are two primary ways of addressing a driveItem resource:
> 
> By the driveItem unique identifier using `drive/items/{item-id}`
> By file system path using `/drive/root:/path/to/file`

And take a look at this similar issue https://github.com/beyondstorage/go-service-gdrive/issues/11

**Comment by Xuanwo** [comment]
See go-service-gdrive RFC-14 for more info: https://github.com/beyondstorage/go-service-gdrive/blob/master/docs/rfcs/14-gdrive-for-go-storage-design.md

<blockquote><img src="https://opengraph.githubassets.com/b242b574caece21e0162e4be3cbd369b248cf1fa252a7015f7abb5b45e5904b0/beyondstorage/go-service-gdrive" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/beyondstorage/go-service-gdrive">go-service-gdrive/14-gdrive-for-go-storage-design.md at master · beyondstorage/go-service-gdrive</a></strong></div><div>Google Drive support for go-storage. Contribute to beyondstorage/go-service-gdrive development by creating an account on GitHub.</div></blockquote>

**Comment by Xuanwo** [comment]
Hello, @zxy-lgtm , Is there anything else we can help you with?

**Comment by zxy-lgtm** [comment]
> 你好，@zxy-lgtm，还有什么我们可以帮助你的吗？

In recent days, I modified the SDK to use path instead of ID function. Recently, because onedri only uses oauth2, I am adding OAuth2 support to it.

**Comment by Xuanwo** [comment]
> In recent days, I modified the SDK to use path instead of ID function. Recently, because onedri only uses oauth2, I am adding OAuth2 support to it.

Maybe we can start a draft PR so that @xxchan can give some advice?

**Comment by zxy-lgtm** [comment]
> > 你好，@zxy-lgtm，还有什么我们可以帮助你的吗？
> 
> In recent days, I modified the SDK to use path instead of ID function. Recently, because onedri only uses oauth2, I am adding OAuth2 support to it.

Because I haven't learned oauth2, I'm learning the official onedrive documentation recently:https://docs.microsoft.com/en-us/graph/auth/auth-concepts

<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/graph/auth/auth-concepts">Authentication and authorization basics for Microsoft Graph - Microsoft Graph</a></strong></div><div>To call Microsoft Graph, your app must acquire an access token from the Microsoft identity platform.</div></blockquote>

**Comment by zxy-lgtm** [comment]
I also saw the implementation of GDrive

**Comment by zxy-lgtm** [comment]
> > In recent days, I modified the SDK to use path instead of ID function. Recently, because onedri only uses oauth2, I am adding OAuth2 support to it.
> 
> Maybe we can start a draft PR so that @xxchan can give some advice?



> question 1: see [beyondstorage/go-service-gdrive#17](https://github.com/beyondstorage/go-service-gdrive/issues/17)
> 
> question 2:
> 
> I found that OneDrive do support file path: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online (If I understand incorrectly, please tell me)
> 
> > There are two primary ways of addressing a driveItem resource:
> > By the driveItem unique identifier using `drive/items/{item-id}`
> > By file system path using `/drive/root:/path/to/file`
> 
> And take a look at this similar issue [beyondstorage/go-service-gdrive#11](https://github.com/beyondstorage/go-service-gdrive/issues/11)

thanks，but  in the method delete does not useful there only have `/me/drive/items/{item-id}`
and also in upload the method put `PUT /me/drive/items/{item-id}/content` when you want to replace an existing item
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online  

<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem">DriveItem - OneDrive API - OneDrive dev center</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content">Upload small files - OneDrive API - OneDrive dev center</a></strong></div></blockquote>

**Comment by zxy-lgtm** [comment]
> > > In recent days, I modified the SDK to use path instead of ID function. Recently, because onedri only uses oauth2, I am adding OAuth2 support to it.
> > 
> > 
> > Maybe we can start a draft PR so that @xxchan can give some advice?
> 
> > question 1: see [beyondstorage/go-service-gdrive#17](https://github.com/beyondstorage/go-service-gdrive/issues/17)
> > question 2:
> > I found that OneDrive do support file path: https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem?view=odsp-graph-online (If I understand incorrectly, please tell me)
> > > There are two primary ways of addressing a driveItem resource:
> > > By the driveItem unique identifier using `drive/items/{item-id}`
> > > By file system path using `/drive/root:/path/to/file`
> > 
> > 
> > And take a look at this similar issue [beyondstorage/go-service-gdrive#11](https://github.com/beyondstorage/go-service-gdrive/issues/11)
> 
> thanks，but in the method delete does not useful there only have `/me/drive/items/{item-id}`
> and also in upload the method put `PUT /me/drive/items/{item-id}/content` when you want to replace an existing item
> https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content?view=odsp-graph-online
> 
> > **[DriveItem - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem)**
> 
> > **[Upload small files - OneDrive API - OneDrive dev center](https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content)**

but I test and find `PUT /me/drive/root:/path:/content` and `DELETE /me/drive/root:/path:` can solve them successfully

<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/onedrive/developer/rest-api/resources/driveitem">DriveItem - OneDrive API - OneDrive dev center</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_put_content">Upload small files - OneDrive API - OneDrive dev center</a></strong></div></blockquote>

**Comment by Xuanwo** [comment]
> but I test and find `PUT /me/drive/root:/path:/content` and `DELETE /me/drive/root:/path:` can solve them successfully

Looks cool.

**Comment by Xuanwo** [comment]
Moved to https://forum.beyondstorage.io/t/topic/240

<blockquote><img src="https://aos-forum.s3.gd2.qingstor.com/original/1X/c20e7258af8443fa28b26c88e7131f6f6b4eddb7.png" width="48" align="right"><div><img src="https://aos-forum.s3.gd2.qingstor.com/optimized/1X/adf1e8fa8e251d6262c51785d3f66df9e93486c5_2_32x32.png" height="14"> BeyondStorage</div><div><strong><a href="https://forum.beyondstorage.io/t/topic/240">Question about OneDrive Storager implement</a></strong></div><div>authorization  Because onedrive uses oauth authentication, an OAuth instance is required to obtain accesstoken. Do we have to do this built-in? My current test environment uses the example of Microsoft Graph Explorer.  If we need to do a built-in authentication process, I think maybe our credential field should be env, which contains similar clientid, clientsecret…    abstract objectID to path  Because the current SDKs are all developed according to OneDrive’s development manual. Onedrive’s AP...</div></blockquote>
